language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

services:
  - mysql
  - postgresql

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit